### ISSUE TITLE
Library version mismatch

### ISSUE THREAD

**Issue by hexonaut** [makerdao/dss-exec-lib#39]
It appears that at least one of the lib dependencies have different versions. Specifically on a fresh clone + test I get:

```
./test.sh
dapp-remappings: error: mismatching packages:
dapp-remappings: error: (1) lib/ds-math/lib/ds-test/src
dapp-remappings: error: (2) lib/ds-proxy/lib/ds-auth/lib/ds-test/src
make: *** [test] Error 1
```

This is after cloning and running `dapp upgrade`.

**Comment by gbalabasquer** [comment]
Actually the error is there, you shouldn't do `dapp upgrade` as you are forcing to update the dependencies to the latest `master`.
Make a fresh clone and run `dapp update`.

**Comment by gbalabasquer** [comment]
It should have actually added a commit doing `dapp upgrade`.

**Comment by hexonaut** [comment]
Oops you're right. Mixed up `update` and `upgrade`. Closing.
